# Site settings
title: Lin Blog
SEOTitle: Lin Blog | Blog
header-img: img/home-bg.jpg
email: deng0068@umn.edu
description: "What did I do && What will I do"
keyword: ""
url: "http://linchrisdeng.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     false
zhihu_username:     false
github_username:    linchrisdeng
twitter_username:  false
facebook_username:  false
linkedin_username:  lin-deng-280200137


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
                      

markdown: kramdown # use Github Flavored Markdown !important
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge
  
  math_engine: mathjax
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: #_your_disqus_short_name_

# Duoshuo settings
duoshuo_username: #linblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: #4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: UA-139933717-1      # Format: UA-xxxxxx-xx
ga_domain: linchrisdeng.github.io  #huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Hello World! Show me what you got"
sidebar-avatar: /img/sidebar_img.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },
    {
        title: "Foo",
        href: "#"
    },
    {
        title: "Bar",
        href: "#"
    },
    {
        title: "Example Friends",
        href: "#"
    },
    {
        title: "It helps SEO",
        href: "#"
    }
]
